"""removing current unused models and adding all used models

Revision ID: 02a7aa767b3a
Revises: b777c9a84ec1
Create Date: 2026-08-10 11:44:44.858367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a7aa767b3a'
down_revision: Union[str, Sequence[str], None] = 'b777c9a84ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discounts')),
    sa.UniqueConstraint('name', name=op.f('uq_discounts_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_discounts_slug'))
    )
    op.create_table('specification_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specification_keys')),
    sa.UniqueConstraint('slug', name=op.f('uq_specification_keys_slug'))
    )
    op.drop_table('product_categories')
    op.drop_table('repair_jobs')
    op.drop_table('cart_items')
    op.drop_table('machine_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('estimated_shipping_price', sa.FLOAT(), nullable=True),
    sa.Column('estimated_delivery_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=19), nullable=False),
    sa.Column('hourly_rate', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_requests'))
    )
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cart_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items'))
    )
    op.create_table('repair_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('issue_description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), nullable=False),
    sa.Column('cost_estimate', sa.FLOAT(), nullable=True),
    sa.Column('machine_model', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repair_jobs'))
    )
    op.create_table('product_categories',
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_product_categories_category_id_categories')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_categories_product_id_products'))
    )
    op.drop_table('specification_keys')
    op.drop_table('discounts')
    # ### end Alembic commands ###
