"""changes to the user and shopping cart tables and relationships

Revision ID: 38a2897b443c
Revises: eb821aae26f2
Create Date: 2026-07-01 11:18:00.947680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a2897b443c'
down_revision: Union[str, Sequence[str], None] = 'eb821aae26f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
