"""reflect changes to relationship and entities - user, product, categories and shopping cart

Revision ID: 61f70fa168ff
Revises: 38a2897b443c
Create Date: 2026-07-03 08:11:20.673333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f70fa168ff'
down_revision: Union[str, Sequence[str], None] = '38a2897b443c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_product_categories_category_id_categories'), 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_product_categories_product_id_products'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_product_categories_product_id_products'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_product_categories_category_id_categories'), type_='foreignkey')

    # ### end Alembic commands ###
