"""remove redundant column definition in shopping cart model

Revision ID: af1b069025b3
Revises: d499dafc30dd
Create Date: 2026-06-15 11:26:23.158542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1b069025b3'
down_revision: Union[str, Sequence[str], None] = 'd499dafc30dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_carts', schema=None) as batch_op:
        batch_op.alter_column('shipping_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DELIVERY', 'PICKUP', name='shippingtypes'),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_shopping_carts_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_carts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shopping_carts_user_id_users'), type_='foreignkey')
        batch_op.alter_column('shipping_type',
               existing_type=sa.Enum('DELIVERY', 'PICKUP', name='shippingtypes'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
