"""add new models

Revision ID: b777c9a84ec1
Revises: 61f70fa168ff
Create Date: 2026-08-10 11:40:44.143539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b777c9a84ec1'
down_revision: Union[str, Sequence[str], None] = '61f70fa168ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specification_keys')
    op.drop_table('product_specifications')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categories_slug'), ['slug'])

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_categories_product_id_products'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_product_categories_category_id_categories'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_product_categories_category_id_categories'), 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_product_categories_product_id_products'), 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_categories_product_id_products'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_product_categories_category_id_categories'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_product_categories_category_id_categories'), 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_product_categories_product_id_products'), 'products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_slug'), type_='unique')

    op.create_table('product_specifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('specification_id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_specifications'))
    )
    op.create_table('specification_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specification_keys'))
    )
    # ### end Alembic commands ###
