"""adding associative tables

Revision ID: d1b78af59ced
Revises: 02a7aa767b3a
Create Date: 2026-08-10 11:46:29.273885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b78af59ced'
down_revision: Union[str, Sequence[str], None] = '02a7aa767b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_discounts',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('discount_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], name=op.f('fk_product_discounts_discount_id_discounts')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_discounts_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'discount_id', name=op.f('pk_product_discounts'))
    )
    op.create_table('product_specifications',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_specifications_product_id_products')),
    sa.ForeignKeyConstraint(['specification_id'], ['specification_keys.id'], name=op.f('fk_product_specifications_specification_id_specification_keys')),
    sa.PrimaryKeyConstraint('product_id', 'specification_id', name=op.f('pk_product_specifications'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_specifications')
    op.drop_table('product_discounts')
    # ### end Alembic commands ###
