"""define default value for image_url and discount id in case of nullable image and set discount_id to init=false

Revision ID: d499dafc30dd
Revises: e328edaa1b9e
Create Date: 2026-06-14 10:57:53.026508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd499dafc30dd'
down_revision: Union[str, Sequence[str], None] = 'e328edaa1b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_product_name'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_products_name'), ['name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_products_name'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_product_name'), ['name'])

    # ### end Alembic commands ###
