"""updating product table to make product name unique

Revision ID: e328edaa1b9e
Revises: d4721925f5d5
Create Date: 2026-06-14 10:05:41.292519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e328edaa1b9e'
down_revision: Union[str, Sequence[str], None] = 'd4721925f5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_product_name', ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_name', type_='unique')

    # ### end Alembic commands ###
