"""add addresses table

Revision ID: eb821aae26f2
Revises: af1b069025b3
Create Date: 2026-06-15 11:56:12.868235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb821aae26f2'
down_revision: Union[str, Sequence[str], None] = 'af1b069025b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_cpf'), ['cpf'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_cpf'), type_='unique')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
